AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
Layout/LineLength:
  Max: 140
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
