name 'observability'
maintainer 'Roger Clevenger'
maintainer_email '70983614+rclevenger-hm@users.noreply.github.com'
license 'Apache-2.0'
description 'Tested Linux observability resources for Prometheus, Grafana, Datadog and Splunk'
version '0.1.0'
chef_version '>= 18.0'
supports 'ubuntu', '>= 22.04'
supports 'rocky', '>= 9.0'
source_url 'https://github.com/rclevenger-hm/chef-observability-cookbook'
issues_url 'https://github.com/rclevenger-hm/chef-observability-cookbook/issues'
